_target_: generic_neuromotor_interface.data.DataSplit

train:
  discrete_gestures_user_000_dataset_000: null
val:
  discrete_gestures_user_001_dataset_000: null
test:
  discrete_gestures_user_002_dataset_000:
    - [1634054147.748458, 1634054327.903508]
