# One dataset each for train, val, and test
# One partition from each dataset
# Useful for quick testing

_target_: generic_neuromotor_interface.data.DataSplit

train:
  handwriting_user_000_dataset_000:
    - [0., .inf]
val:
  handwriting_user_001_dataset_000:
    - [0., .inf]
test:
  handwriting_user_002_dataset_000:
    - [0., .inf]
