# One dataset each for train, val, and test
# Useful for quick testing

_target_: generic_neuromotor_interface.data.DataSplit

train:
  wrist_user_000_dataset_000: null # null means use the entire dataset (no partitioning)
val:
  wrist_user_001_dataset_000: null # null means use the entire dataset (no partitioning)
test:
  wrist_user_002_dataset_000:
    - [1713966045.6641605, 1713966207.9896057]
