_target_: generic_neuromotor_interface.data_module.WindowedEmgDataModule
window_length: 16_000 # 8 seconds at 2kHz
stride: 16_000  # match window_length to minimize overlapping samples
batch_size: 128

# Multiple data workers can fail on some machines. See:
# https://stackoverflow.com/questions/60684061/typeerror-h5py-objects-cannot-be-pickled
num_workers: 0

transform:
  _target_: generic_neuromotor_interface.transforms.DiscreteGesturesTransform
  # 40 ms pulses centered 100 ms after the event
  pulse_durations:
    index_press: [0.08, 0.12]
    index_release: [0.08, 0.12]
    middle_press: [0.08, 0.12]
    middle_release: [0.08, 0.12]
    thumb_up: [0.08, 0.12]
    thumb_in: [0.08, 0.12]
    thumb_click: [0.08, 0.12]
    thumb_down: [0.08, 0.12]
    thumb_out: [0.08, 0.12]

data_location: ${data_location}

emg_augmentation:
  _target_: generic_neuromotor_interface.augmentation.RotationAugmentation
  rotation: 2
