# conda env create -f environment.yml

name: neuromotor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - black==24.4.2
  - click==8.1.7
  - flake8==7.0.0
  - h5py==3.11.0
  - hydra-core==1.3.2
  - hypothesis==6.97.6
  - jupyterlab=4.1.8
  - levenshtein==0.26.1
  - mypy==1.10.0
  - numba==0.60.0
  - numpy==1.26.4
  - pandas==2.2.2
  - pip==24.0
  - pre-commit==3.7.1
  - pytables=3.10.1
  - pytest==8.2.2
  - python-levenshtein==0.26.1
  - python==3.10.13
  - pytorch-lightning==2.2.2
  - pytorch::pytorch==2.3.1
  - pyyaml==6.0.1
  - scipy==1.13.1
  - trio==0.25.1
  - unidecode==1.3.8
  - pip:
      - matplotlib==3.9.2
