# Workflow run that uses prod data and checkpoints
# (uses real [small] dataset and real checkpoints)

# Uses a CPU runner and tests not_cuda, real_data, and small data subset

name: CPU Integration Tests (Real Data)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main


jobs:
  cpu-integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'run-full-ci-cpu') || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: 8-core-ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          auto-update-conda: true
          python-version: "3.12"
          miniconda-version: "latest"
          activate-environment: neuromotor
          environment-file: environment.yml

      - name: Install local package
        shell: bash -el {0}
        run: |
          conda activate neuromotor
          pip install -e .

      - name: Run pre-commit checks
        shell: bash -el {0}
        run: |
          conda activate neuromotor
          pre-commit run --all-files

      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        shell: bash -el {0}
        run: |
          conda activate neuromotor
          pytest

      - name: Run integration tests (with real data + checkpoints) [CPU]
        shell: bash -el {0}
        run: |
          conda activate neuromotor
          pytest -m "integration and not full_data and not cuda" \
            -vv \
            --durations=10 \
            -rA
