name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        auto-update-conda: true
        python-version: "3.10"
        miniconda-version: "latest"
        activate-environment: neuromotor
        environment-file: environment.yml

    - name: Install local package
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pip install -e .

    - name: Run pre-commit checks
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pre-commit run --all-files

    - name: Run tests
      shell: bash -el {0}
      run: |
        conda activate neuromotor
        pytest
